#!/usr/bin/env python3
"""
Generates src/PW64Editor.Core/Text/TextReferences.g.cs from the Pilotwings 64 decompilation.

For every text ID of the US version (src/app/text_data.h) it records which source files of the
game use it. The editor uses this to sort texts into categories ("Options menu", "File select", ...).
Only facts (names and file names) are taken from the decompilation, no code.

Usage:
    python3 tools/generate_text_references.py <path to Pilotwings64Decomp checkout>

Decompilation: https://github.com/gcsmith/Pilotwings64Decomp (MIT license)
"""
import pathlib
import re
import sys


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)

    decomp = pathlib.Path(sys.argv[1])
    header = (decomp / "src/app/text_data.h").read_text(encoding="utf-8")

    # The header has one enum for JP and one for US, separated by #else. We need the US one.
    us_part = header[header.index("#else"):]
    names = re.findall(r"TEXT_(\w+)\s*=\s*0x[0-9A-Fa-f]+", us_part)

    sources = {
        path.relative_to(decomp / "src").as_posix(): path.read_text(encoding="utf-8", errors="replace")
        for path in sorted((decomp / "src").rglob("*.c"))
    }

    lines = []
    for name in names:
        pattern = re.compile(r"\bTEXT_" + re.escape(name) + r"\b")
        files = [file for file, text in sources.items() if pattern.search(text)]
        if files:
            joined = ", ".join(f'"{f}"' for f in files)
            lines.append(f'        ["{name}"] = [{joined}],')

    output = (
        "// <auto-generated>\n"
        "// Generated by tools/generate_text_references.py from the Pilotwings 64 decompilation\n"
        "// (https://github.com/gcsmith/Pilotwings64Decomp, MIT license). Do not edit by hand;\n"
        "// run the script again instead.\n"
        "// </auto-generated>\n"
        "\n"
        "namespace PW64Editor.Core.Text;\n"
        "\n"
        "/// <summary>\n"
        "/// Which source files of the game use each text (by its name in the text file).\n"
        "/// Texts that are not listed are looked up with names the game builds at runtime.\n"
        "/// </summary>\n"
        "internal static class TextReferences\n"
        "{\n"
        "    public static readonly IReadOnlyDictionary<string, string[]> SourceFiles = new Dictionary<string, string[]>\n"
        "    {\n"
        + "\n".join(lines) + "\n"
        "    };\n"
        "}\n"
    )

    target = pathlib.Path(__file__).resolve().parent.parent / "src/PW64Editor.Core/Text/TextReferences.g.cs"
    target.write_text(output, encoding="utf-8", newline="\n")
    print(f"Wrote {len(lines)} of {len(names)} text names to {target}")


if __name__ == "__main__":
    main()
