using System.Text.RegularExpressions;

namespace PW64Editor.Core.Text;

/// <summary>
/// Sorts game texts into categories by where they appear in the game.
/// </summary>
/// <remarks>
/// <para>Two sources of information are combined:</para>
/// <list type="number">
///   <item>The developers' naming scheme. Mission texts are not referenced directly in the code;
///         the game builds their names at runtime from class, vehicle and mission number, e.g.
///         "A_HG_2_M" = class A, hang glider, mission 2, mission description.</item>
///   <item>For all other texts: which source files of the decompilation use them
///         (<see cref="TextReferences"/>, generated by tools/generate_text_references.py).</item>
/// </list>
/// <para>Abbreviations in the names:</para>
/// <code>
/// Classes:  E = Beginner, B = Class B, A = Class A, P = Pilot class
/// Vehicles: HG = Hang Glider, RP = Rocket Belt, GC = Gyrocopter, BD = Birdman,
///           EX = bonus game (A = Cannonball, B = Sky Diving, P = Jumble Hopper),
///           SD = Sky Diving, CB = Cannonball, HP = Jumble Hopper
/// Kinds:    N = name, M = mission description, H = hint, A = tutorial page,
///           S1/S2 = score sheet, S3 = badge requirement
/// </code>
/// </remarks>
public static partial class TextCatalog
{
    private static readonly string[] AreaNames =
    [
        "Menus and screens", "In flight", "Hang Glider", "Rocket Belt", "Gyrocopter", "Birdman",
        "Cannonball", "Sky Diving", "Jumble Hopper", "Badges", "Other",
    ];

    private static readonly Dictionary<string, string> Vehicles = new()
    {
        ["HG"] = "Hang Glider", ["RP"] = "Rocket Belt", ["GC"] = "Gyrocopter", ["BD"] = "Birdman",
        ["SD"] = "Sky Diving", ["CB"] = "Cannonball", ["HP"] = "Jumble Hopper",
    };

    /// <summary>Bonus games ("EX") are identified by the class letter.</summary>
    private static readonly Dictionary<string, string> BonusGames = new()
    {
        ["A"] = "Cannonball", ["B"] = "Sky Diving", ["P"] = "Jumble Hopper",
    };

    private static readonly Dictionary<string, (string Name, int Order)> Classes = new()
    {
        ["E"] = ("Beginner class", 1), ["A"] = ("Class A", 2), ["B"] = ("Class B", 3), ["P"] = ("Pilot class", 4),
        ["BONUS"] = ("Bonus games", 5),
    };

    private static readonly Dictionary<string, string> Kinds = new()
    {
        ["N"] = "name", ["M"] = "description", ["H"] = "hint",
    };

    private static readonly Dictionary<string, string> Badges = new()
    {
        ["GREAT"] = "Perfect score message", ["PERFECT"] = "Perfect score requirement",
        ["GOLD"] = "Gold badge requirement", ["SILVER"] = "Silver badge requirement",
        ["BLONDS"] = "Bronze badge requirement", // sic, "blonds" in the original names
    };

    /// <summary>
    /// Areas and sections for texts that are used directly in the code, by source file.
    /// Earlier entries win when a text is used in several files.
    /// </summary>
    private static readonly (string File, string Area, string Section)[] SourceFileCategories =
    [
        ("app/title_screen.c", "Menus and screens", "Title screen"),
        ("app/file_menu.c", "Menus and screens", "File select"),
        ("app/options.c", "Menus and screens", "Options"),
        ("app/pilot_select.c", "Menus and screens", "Pilot select"),
        ("app/code_61A60.c", "Menus and screens", "Pilot names"),
        ("app/level_select.c", "Menus and screens", "Vehicle and class select"),
        ("app/test_summary.c", "Menus and screens", "Test summary"),
        ("app/results.c", "Menus and screens", "Results"),
        ("app/total_results.c", "Menus and screens", "Results"),
        ("app/replay_screen.c", "Menus and screens", "Replay and pause menu"),
        ("app/snap.c", "Menus and screens", "Photos"),
        ("app/credits.c", "Menus and screens", "Ending"),
        ("app/hang_glider1.c", "Hang Glider", "In-flight messages"),
        ("app/hang_glider2.c", "Hang Glider", "In-flight messages"),
        ("app/hang_glider_sound.c", "Hang Glider", "In-flight messages"),
        ("app/rocket_belt.c", "Rocket Belt", "In-flight messages"),
        ("app/gyrocopter.c", "Gyrocopter", "In-flight messages"),
        ("app/falco.c", "Gyrocopter", "In-flight messages"), // Meca Hawk
        ("app/skydiving.c", "Sky Diving", "In-flight messages"),
        ("app/cannonball.c", "Cannonball", "In-flight messages"),
        ("app/rings.c", "In flight", "Rings, targets and balloons"),
        ("app/targets.c", "In flight", "Rings, targets and balloons"),
        ("app/balls.c", "In flight", "Rings, targets and balloons"),
        ("app/game.c", "In flight", "General messages"),
    ];

    /// <summary>Names that are used at runtime only, but whose purpose is clear.</summary>
    private static readonly Dictionary<string, (string Area, string Section, string Description)> KnownNames = new()
    {
        ["HANG"] = ("Menus and screens", "Vehicle names", "Hang Glider"),
        ["ROCKET"] = ("Menus and screens", "Vehicle names", "Rocket Belt"),
        ["GYRO"] = ("Menus and screens", "Vehicle names", "Gyrocopter"),
        ["SKYDIVER"] = ("Menus and screens", "Vehicle names", "Sky Diving"),
        ["CANNON"] = ("Menus and screens", "Vehicle names", "Cannonball"),
        ["WINDOW1"] = ("Menus and screens", "Replay and pause menu", "Pause menu"),
        ["WINDOW2"] = ("Menus and screens", "Replay and pause menu", "Pause menu with photo option"),
        ["CONTINUE"] = ("Menus and screens", "Replay and pause menu", string.Empty),
        ["CRASH"] = ("In flight", "General messages", string.Empty),
        ["OUT"] = ("In flight", "General messages", string.Empty),
        ["MUSHI"] = ("In flight", "General messages", string.Empty),
        ["LAND_GAI"] = ("In flight", "General messages", string.Empty),
        ["STRIKE"] = ("In flight", "General messages", string.Empty),
    };

    /// <summary>Determines the category of a text by its name.</summary>
    public static TextCategory Categorize(string name)
    {
        string[] sourceFiles = TextReferences.SourceFiles.GetValueOrDefault(name, []);

        Match m;

        // Mission name / description / hint: A_HG_2_M
        if ((m = MissionPattern().Match(name)).Success && Classes.ContainsKey(m.Groups[1].Value))
        {
            string cls = m.Groups[1].Value, vehicle = m.Groups[2].Value, number = m.Groups[3].Value, kind = m.Groups[4].Value;

            if (vehicle == "EX")
            {
                return BonusGames.TryGetValue(cls, out string? game)
                    ? Make(game, "Levels", 1, $"Level {number} {Kinds[kind]}", $"{number}{KindOrder(kind)}", sourceFiles)
                    : Other(name, sourceFiles);
            }

            (string className, int classOrder) = Classes[cls];
            return Make(Vehicles[vehicle], className, classOrder, $"Mission {number} {Kinds[kind]}", $"{number}{KindOrder(kind)}", sourceFiles);
        }

        // Tutorial page: HG_6_A
        if ((m = TutorialPattern().Match(name)).Success)
        {
            int page = int.Parse(m.Groups[2].Value, System.Globalization.CultureInfo.InvariantCulture);
            return Make(Vehicles[m.Groups[1].Value], "Tutorial", 0, $"Tutorial page {page}", $"{page:D2}", sourceFiles);
        }

        // Score sheet of a mission: HG_B3_S1, GC_E_S2
        if ((m = ScoreSheetPattern().Match(name)).Success)
        {
            (string className, int classOrder) = Classes[m.Groups[2].Value];
            string mission = m.Groups[3].Value.Length > 0 ? $" mission {m.Groups[3].Value}" : string.Empty;
            return Make(Vehicles[m.Groups[1].Value], "Score sheets", 6,
                $"{className}{mission}, sheet {m.Groups[4].Value}",
                $"{classOrder}{m.Groups[3].Value}{m.Groups[4].Value}", sourceFiles);
        }

        // Score sheet of a bonus game level: SD_L123_S1, HP_L2_S1
        if ((m = BonusScoreSheetPattern().Match(name)).Success)
        {
            string levels = m.Groups[2].Value;
            string which = levels.Length > 1 ? "all levels" : $"level {levels}";
            return Make(Vehicles[m.Groups[1].Value], "Score sheets", 6, $"Score sheet {m.Groups[3].Value}, {which}",
                $"{levels}{m.Groups[3].Value}", sourceFiles);
        }

        // Birdman: BD_ALL_S1
        if ((m = BirdmanSheetPattern().Match(name)).Success)
        {
            return Make("Birdman", "Score sheets", 6, $"Message {m.Groups[1].Value}", m.Groups[1].Value, sourceFiles);
        }

        // Badge requirements: A_S3_GOLD, BONUS_S3_SILVER
        if ((m = BadgePattern().Match(name)).Success && Classes.TryGetValue(m.Groups[1].Value, out var badgeClass))
        {
            string badge = m.Groups[2].Value;
            int badgeOrder = Array.IndexOf(["BLONDS", "SILVER", "GOLD", "PERFECT", "GREAT"], badge);
            return Make("Badges", badgeClass.Name, badgeClass.Order, Badges[badge], $"{badgeOrder}", sourceFiles);
        }

        if (KnownNames.TryGetValue(name, out var known))
        {
            return Make(known.Area, known.Section, SectionOrderOf(known.Section), known.Description, name, sourceFiles);
        }

        // Used directly in the code: categorize by the most specific source file.
        foreach ((string file, string area, string section) in SourceFileCategories)
        {
            if (sourceFiles.Contains(file))
            {
                return Make(area, section, SectionOrderOf(section), string.Empty, name, sourceFiles);
            }
        }

        if (sourceFiles.Length > 0)
        {
            return Make("In flight", "General messages", SectionOrderOf("General messages"), string.Empty, name, sourceFiles);
        }

        return Other(name, sourceFiles);
    }

    /// <summary>
    /// Sort position of a section that comes from the source file list. "Vehicle names" has no
    /// source file and goes first; all others come after the mission sections (0-6).
    /// </summary>
    private static int SectionOrderOf(string section)
    {
        int index = Array.FindIndex(SourceFileCategories, c => c.Section == section);
        return index < 0 ? 0 : 10 + index;
    }

    private static TextCategory Other(string name, string[] sourceFiles) =>
        Make("Other", "Not assigned yet", 0, string.Empty, name, sourceFiles);

    private static TextCategory Make(string area, string section, int sectionOrder, string description, string sortKey, string[] sourceFiles)
    {
        int areaOrder = Array.IndexOf(AreaNames, area);
        return new TextCategory(area, areaOrder < 0 ? AreaNames.Length : areaOrder, section, sectionOrder, description, sortKey, sourceFiles);
    }

    /// <summary>Name first, then description, then hint.</summary>
    private static int KindOrder(string kind) => kind switch { "N" => 0, "M" => 1, _ => 2 };

    [GeneratedRegex(@"^(E|B|A|P)_(HG|RP|GC|BD|EX)_(\d+)_(N|M|H)$")]
    private static partial Regex MissionPattern();

    [GeneratedRegex(@"^(HG|RP|GC)_(\d+)_A$")]
    private static partial Regex TutorialPattern();

    [GeneratedRegex(@"^(HG|RP|GC)_(E|B|A|P)(\d?)_S([12])$")]
    private static partial Regex ScoreSheetPattern();

    [GeneratedRegex(@"^(SD|CB|HP)_L(\d+)_S([12])$")]
    private static partial Regex BonusScoreSheetPattern();

    [GeneratedRegex(@"^BD_ALL_S(\d)$")]
    private static partial Regex BirdmanSheetPattern();

    [GeneratedRegex(@"^(E|B|A|P|BONUS)_S3_(GREAT|PERFECT|GOLD|SILVER|BLONDS)$")]
    private static partial Regex BadgePattern();
}
